name: sqlfmt
title: sqlfmt
version: "1.2.7"
source-code: https://github.com/GrantFBarnes/sqlfmt
license: GPL-3.0-only
icon: snap/icon.png
summary: CLI to format SQL
description: |
  A command line interface tool to format SQL.
  Arguments allow for configuration on how to format.
  Can use stdin/stdout or files for input/output.

base: core24
grade: stable
confinement: strict

parts:
  sqlfmt:
    plugin: rust
    source: .

apps:
  sqlfmt:
    command: bin/sqlfmt
    plugs:
      - home
