name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-rust:
    name: Build Rust (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlfmt-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/sqlfmt*

  build-vsix:
    name: Build VSIX
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Install dependencies
        run: npm ci
        working-directory: ./vsce
      - name: Package VSIX
        run: vsce package
        working-directory: ./vscode-extension
      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-vsix
          path: ./vscode-extension/*.vsix

  release:
    name: Create Release
    needs: [build-rust, build-vsix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/sqlfmt-*/sqlfmt*
            ./artifacts/extension-vsix/*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
